version: '3.8'

services:
  kong:
    image: kong:3.6.0
    container_name: kong_gateway
    ports:
      - "8080:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong.yml:/kong/kong.yml
